


apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  namespace: monitoring

data:
  server.port: "7000"
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/users
  spring.datasource.initialization-mode: always


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user-deployment
  namespace: monitoring
  
  labels:
    app:  user-deployment
spec:
  selector:
    matchLabels:
      app: user-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app:  user-deployment
    spec:

      containers:
      - name:  user-deployment
        #
        #   Error: Failed to fetch image
        #
        #
        image:  philipasd/user_service:0.0.0
        imagePullPolicy: Always

        ports:
        - name: http
          containerPort:  7000
          protocol: TCP
          
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: http
        #   initialDelaySeconds: 300
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: http
        #   initialDelaySeconds: 60
        #   periodSeconds: 10

        env:
          - name:  SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  SPRING_DATASOURCE_USERNAME
          - name:  SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  server.port
          - name:  SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  SPRING_PROFILES_ACTIVE
          - name:  SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  SPRING_DATASOURCE_PASSWORD
          - name:  SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  SPRING_DATASOURCE_URL
          - name:  SPRING.DATASOURCE.INITIALIZATION-MODE
            valueFrom:
              configMapKeyRef:
                name:  user-configmap
                key:  spring.datasource.initialization-mode